#ifndef extrapcoeffs__h
#define extrapcoeffs__h
#include <initializer_list>
#include "OdesException.hpp"
using namespace std;
namespace odes{
  template<int nsteps,class Double> void extrapcoeffs(Double* c)
  {
 
    throw OdesException("SymplecticRK::GaussianMethod::extrapcoeffs:",
			"nsteps must be in range [2,16];\nhere we have",
			"nsteps=",nsteps,".");
  }
 
  // include the specialized versions of icoeff, generated by sage.
#include "../sage/generated_coeffs_co.hpp"
};
#endif
