#ifndef icoeffs__h
#define icoeffs__h
#include <initializer_list>
#include "OdesException.hpp"
using namespace std;
namespace odes{
  template<int nsteps,class Double> void icoeffs(Double* a,Double* b)
  {
   // static assertion does not give always clear messages; so we prefer to
   // throw an exception at run time:
    throw OdesException("SymplecticRK::GaussianMethod::icoeffs:",
			"nsteps must be in range [2,16];\nhere we have",
			"nsteps=",nsteps,".");
  }
  
  // include the specialized versions of icoeff, generated by sage.
#include "../sage/generated_coeffs.hpp"
};
#endif
